# Generated by Django 4.0.2 on 2022-02-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_movie_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
    ]
