# Generated by Django 4.0.2 on 2022-02-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_remove_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Durations'),
        ),
    ]
