# Generated by Django 4.0.2 on 2022-02-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_moviereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='review',
        ),
        migrations.AddField(
            model_name='moviereview',
            name='review',
            field=models.ManyToManyField(to='movie_app.Review'),
        ),
    ]
