# Generated by Django 4.0.2 on 2022-02-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_remove_moviereview_review_moviereview_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ManyToManyField(to='movie_app.Movie'),
        ),
    ]
