# Generated by Django 4.0.2 on 2022-02-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0012_remove_review_movie_review_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='review',
        ),
        migrations.AddField(
            model_name='moviereview',
            name='review',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.review'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie'),
        ),
    ]
