# Generated by Django 4.0.2 on 2022-02-21 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0013_remove_moviereview_review_moviereview_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.review'),
        ),
    ]
