# Generated by Django 4.0.2 on 2022-02-21 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0014_alter_moviereview_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieReview',
        ),
    ]
